Destructors should not throw exceptions
le1ca/Inotify_cpp pull request #3
Opened 2017-09-13 15:06 UTC by yisonPylkita

Issue discussion #1

2017-11-07 14:52 UTC, Bu11etmagnet requested changes
The fd should be closed even if we don't throw.

2017-11-07 14:52 UTC, Bu11etmagnet commented on inotify/InotifyManager.cpp
> -	if(fd != -1 && close(this->fd)){
This leaks the fd (it is never closed).

2019-02-27 10:04 UTC, yisonPylkita commented on inotify/InotifyManager.cpp
> -	if(fd != -1 && close(this->fd)){
Thanks for noticing. Fixed

2019-02-27 10:05 UTC, yisonPylkita commented
@Bu11etmagnet Should be fine now, right ?

2019-02-27 11:33 UTC, Bu11etmagnet commented
@yisonPylkita I can't see anything wrong with it.

2019-02-27 11:55 UTC, yisonPylkita commented
@le1ca Can you merge this now ?

2019-02-28 00:51 UTC, tmick0 approved these changes

2019-02-28 00:51 UTC, tmick0 commented on inotify/InotifyManager.cpp
> -	if(fd != -1 && close(this->fd)){
I think we still ought to attempt to close this fd, and maybe emit a warning if that fails

2019-02-28 00:52 UTC, merged

2019-02-28 00:52 UTC, le1ca commented
Thanks for the fixes everyone, it's merged now